# Generated by Django 5.0.2 on 2024-02-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
