# Generated by Django 5.0.2 on 2024-02-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0002_alter_articles_added_alter_articles_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='source',
            field=models.TextField(),
        ),
    ]
